2021-06-15 15:10:41,574 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2021-06-15 15:10:42,970 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 1.6324777992736008e-41, best pos: [4.03848547e-21 1.24149355e-22]
2021-06-15 15:43:40,278 - pyswarms.single.local_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9, 'k': 2, 'p': 2}
2021-06-15 15:43:41,890 - pyswarms.single.local_best - INFO - Optimization finished | best cost: 1.1870815271321057e-42, best pos: [-9.92785395e-22 -4.48841495e-22]
2021-06-15 18:39:44,672 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
2021-06-15 18:40:12,349 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
2021-06-15 18:40:19,793 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
2021-06-15 20:33:34,471 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
2021-06-15 21:42:52,441 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
2021-06-15 21:48:39,037 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (10,)
Traceback (most recent call last):
  File "C:\Users\kmat9\anaconda3\lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
  File "mtrand.pyx", line 1121, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 541, in numpy.random._common.cont
  File "_common.pyx", line 458, in numpy.random._common.cont_broadcast_2
  File "__init__.pxd", line 741, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape
